cd /d "%~dp0"

set OSUTILS_PATH=..\..\..\..\..\..\..\..\..\..\Personal data\Software\Other\Software development\C++\Robotics\Current\OSUtils

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\ArduPilot2Waypoints\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\ArduPilot2Waypoints\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\ArduPilot2Waypoints\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\ArduPilot2Waypoints\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\ArduPilot2Waypoints\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\ArduPilot2Waypoints\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\CSV2lognav_WRSC2016\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\CSV2lognav_WRSC2016\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\CSV2lognav_WRSC2016\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\CSV2lognav_WRSC2016\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\CSV2lognav_WRSC2016\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\CSV2lognav_WRSC2016\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\downgradelogstate\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\downgradelogstate\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\downgradelogstate\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\downgradelogstate\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\downgradelogstate\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\downgradelogstate\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\GPSSMS2KML\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\GPSSMS2KML\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\GPSSMS2KML\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\GPSSMS2KML\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\GPSSMS2KML\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\GPSSMS2KML\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\KML2Waypoints\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\KML2Waypoints\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\KML2Waypoints\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\KML2Waypoints\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\KML2Waypoints\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\KML2Waypoints\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\LocalBoxes2KML\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\LocalBoxes2KML\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\LocalBoxes2KML\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\LocalBoxes2KML\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\LocalBoxes2KML\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\LocalBoxes2KML\OSTime.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\LocalBoxes2KML\AxisOptions.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\LocalBoxes2KML\CoordSystem.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\LocalBoxes2KML\CoordSystem2Img.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\LocalBoxes2KML\CoordSystemChg.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\lognav2KML\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\lognav2KML\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\lognav2KML\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\lognav2KML\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\lognav2KML\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\lognav2KML\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\MDM2CSV\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\MDM2CSV\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\MDM2CSV\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\MDM2CSV\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\MDM2CSV\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\MDM2CSV\OSTime.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\MDM2CSV\AxisOptions.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\MDM2CSV\CoordSystem.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\MDM2CSV\CoordSystem2Img.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\MDM2CSV\CoordSystemChg.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\MDMRNG2KML_clampToGround\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\MDMRNG2KML_clampToGround\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\MDMRNG2KML_clampToGround\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\MDMRNG2KML_clampToGround\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\MDMRNG2KML_clampToGround\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\MDMRNG2KML_clampToGround\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\MT2KML\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\MT2KML\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\MT2KML\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\MT2KML\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\MT2KML\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\MT2KML\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\MT2NMEA\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\MT2NMEA\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\MT2NMEA\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\MT2NMEA\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\MT2NMEA\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\MT2NMEA\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\NMEA2CSV\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\NMEA2CSV\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\NMEA2CSV\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\NMEA2CSV\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\NMEA2CSV\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\NMEA2CSV\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\NMEA2CSV_WRSC2016\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\NMEA2CSV_WRSC2016\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\NMEA2CSV_WRSC2016\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\NMEA2CSV_WRSC2016\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\NMEA2CSV_WRSC2016\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\NMEA2CSV_WRSC2016\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\NMEA2XML_WRSC2015\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\NMEA2XML_WRSC2015\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\NMEA2XML_WRSC2015\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\NMEA2XML_WRSC2015\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\NMEA2XML_WRSC2015\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\NMEA2XML_WRSC2015\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\SBG2MT\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\SBG2MT\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\SBG2MT\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\SBG2MT\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\SBG2MT\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\SBG2MT\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\upgradelogstate\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\upgradelogstate\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\upgradelogstate\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\upgradelogstate\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\upgradelogstate\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\upgradelogstate\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\Waypoints2Ardupilot\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\Waypoints2Ardupilot\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\Waypoints2Ardupilot\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\Waypoints2Ardupilot\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\Waypoints2Ardupilot\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\Waypoints2Ardupilot\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\Waypoints2KML\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\Waypoints2KML\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\Waypoints2KML\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\Waypoints2KML\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\Waypoints2KML\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\Waypoints2KML\OSTime.h"

copy /B /Y /Z "%OSUTILS_PATH%\OSCore.c" .\Waypoints2mission\OSCore.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSCore.h" .\Waypoints2mission\OSCore.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.c" .\Waypoints2mission\OSMisc.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSMisc.h" .\Waypoints2mission\OSMisc.h"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.c" .\Waypoints2mission\OSTime.c"
copy /B /Y /Z "%OSUTILS_PATH%\OSTime.h" .\Waypoints2mission\OSTime.h"

pause
